#include "MonobarLiftStateControllerFactoryFunctionWrapper.h"

MonobarLiftStateControllerFactoryFunctionWrapper::MonobarLiftStateControllerFactoryFunctionWrapper(void)
{}

MonobarLiftStateControllerFactoryFunctionWrapper::~MonobarLiftStateControllerFactoryFunctionWrapper(void)
{}
