#include "ReverseDoubleForebarLiftStateControllerWrapper.h"

ReverseDoubleForebarLiftStateControllerWrapper::ReverseDoubleForebarLiftStateControllerWrapper(void)
{}

ReverseDoubleForebarLiftStateControllerWrapper::~ReverseDoubleForebarLiftStateControllerWrapper(void)
{}
