#include "TrayLiftStateControllerFactoryFunctionWrapper.h"

TrayLiftStateControllerFactoryFunctionWrapper::TrayLiftStateControllerFactoryFunctionWrapper(void)
{}

TrayLiftStateControllerFactoryFunctionWrapper::~TrayLiftStateControllerFactoryFunctionWrapper(void)
{}
